services:
  nextjs:
    container_name: flopcoin-nextjs-container
    image: flopcoin-nextjs:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CF_TUNNEL_ID: ${CF_TUNNEL_ID}
        CF_ZONE_ID: ${CF_ZONE_ID}
        CF_API_TOKEN: ${CF_API_TOKEN}
    ports:
      - "3006:3000"
    restart: unless-stopped
    networks:
      - flopcoin

  cloudflared:
    container_name: flopcoin-cloudflared-container
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    volumes:
      - ./config/cloudflared:/etc/cloudflared
    networks:
      - flopcoin

networks:
  flopcoin:
    driver: bridge